#!/usr/bin/env bash
# 扫 plans/ 下所有 *.json，生成 zsh 函数到 aliases.zsh。
# 命令名默认为 claude4<filename>；plan 文件里 ._proxy.command 可覆盖。

set -euo pipefail

PROXY_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PLANS_DIR="$PROXY_DIR/plans"
OUT="$PROXY_DIR/aliases.zsh"

if ! command -v jq >/dev/null 2>&1; then
  echo "install: jq is required (brew install jq)" >&2
  exit 1
fi

chmod +x "$PROXY_DIR/claude-proxy.sh"

{
  echo "# Auto-generated by claude-proxy/install.sh — do not edit by hand."
  echo "# Re-run install.sh after adding/removing/renaming plans/*.json."
  echo ""
  find "$PLANS_DIR" -maxdepth 1 -name '*.json' -print0 | \
    while IFS= read -r -d '' f; do
      plan=$(basename "$f" .json)
      cmd=$(jq -r '._proxy.command // empty' "$f")
      [[ -z "$cmd" ]] && cmd="claude4${plan}"
      printf '%s() { "%s/claude-proxy.sh" "%s" "$@"; }\n' \
        "$cmd" "$PROXY_DIR" "$plan"
    done
} > "$OUT"

echo "✔ Generated: $OUT"
echo ""
echo "Installed commands:"
find "$PLANS_DIR" -maxdepth 1 -name '*.json' -print0 | \
  while IFS= read -r -d '' f; do
    plan=$(basename "$f" .json)
    cmd=$(jq -r '._proxy.command // empty' "$f")
    [[ -z "$cmd" ]] && cmd="claude4${plan}"
    printf '  %-20s -> plan: %s\n' "$cmd" "$plan"
  done
echo ""
echo "Next step — add this to ~/.zshrc (once):"
echo ""
echo "  source \"$OUT\""
echo ""
echo "Then reload: exec zsh"
